import { CategoryInfo, Product } from "@/lib/types";


export const CATEGORY_INFO: CategoryInfo[] = [
  {
    key: "hfd-duty",
    label: "HFD Duty",
    description: "Station-ready performance apparel, uniforms, and training layers built for everyday service.",
  },
  {
    key: "hfd-explorers",
    label: "HFD Explorers",
    description: "Youth and academy-forward essentials for the next generation of first responders.",
  },
  {
    key: "off-duty-fire",
    label: "Off Duty Fire",
    description: "Lifestyle-driven fire culture pieces for off-shift wear and community events.",
  },
  {
    key: "gba-baseball",
    label: "GBA Baseball",
    description: "Team and game-day collection with athletic cuts and durable materials.",
  },
  {
    key: "flow-iv",
    label: "Flow IV",
    description: "EMS-inspired designs focused on comfort, mobility, and medic identity.",
  },
  {
    key: "patriot-essentials",
    label: "Patriot Essentials",
    description: "Caps, accessories, and staples for supporters of service and freedom.",
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "dfi-001",
    slug: "explorers-crew-neck-gildan-100-cotton",
    title: "Explorers Crew Neck Gildan 100% cotton",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-explorers",
    priceCents: 2000,
    badge: "Best Seller",
    tags: ["explorers"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/541/image_1024/Explorers%20Crew%20Neck%20Gildan%20100%25%20cotton%20%28Small%2C%20white%29?unique=c717a7a",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/541/image_1024/Explorers%20Crew%20Neck%20Gildan%20100%25%20cotton%20%28Small%2C%20white%29?unique=c717a7a", "/assets/drive/998413f0-7aa6-4026-8d95-da614621f484-png-1wpbYa.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/explorers-crew-neck-gildan-100-cotton-53",
    source: "demo",
  },
  {
    id: "dfi-002",
    slug: "explorers-red-kap-pant",
    title: "Explorers Red Kap Pant",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-explorers",
    priceCents: 3000,
    tags: ["explorers"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/577/image_1024/Explorers%20Red%20Kap%20Pant%20%2830X26%29?unique=cac99d2",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/577/image_1024/Explorers%20Red%20Kap%20Pant%20%2830X26%29?unique=cac99d2", "/assets/drive/ed846aac-ef75-4841-9b61-f16fa9876f19-png-1jBXR0.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/explorers-red-kap-pant-56",
    source: "demo",
  },
  {
    id: "dfi-003",
    slug: "explorers-red-kap-top",
    title: "Explorers Red Kap Top",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-explorers",
    priceCents: 2000,
    tags: ["explorers"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/572/image_1024/Explorers%20Red%20Kap%20Top%20%28Small%29?unique=292dda8",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/572/image_1024/Explorers%20Red%20Kap%20Top%20%28Small%29?unique=292dda8", "/assets/drive/screenshot-2026-04-19-at-8-04-00-pm-png-19n7wU.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/explorers-red-kap-top-55",
    source: "demo",
  },
  {
    id: "dfi-004",
    slug: "explorers-t-shirt-gildan-100-cotton",
    title: "Explorers T shirt Gildan 100% cotton",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-explorers",
    priceCents: 1200,
    tags: ["explorers", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/525/image_1024/Explorers%20T%20shirt%20Gildan%20100%25%20cotton%20%28Small%2C%20white%29?unique=05626c1",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/525/image_1024/Explorers%20T%20shirt%20Gildan%20100%25%20cotton%20%28Small%2C%20white%29?unique=05626c1", "/assets/drive/screenshot-2026-04-12-at-7-07-00-pm-png-1a7ZUv.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/explorers-t-shirt-gildan-100-cotton-52",
    source: "demo",
  },
  {
    id: "dfi-005",
    slug: "explorers-shorts-sport-tech-cotton-blend",
    title: "Explorers shorts Sport Tech Cotton blend",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-explorers",
    priceCents: 1500,
    tags: ["explorers", "shorts"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/590/image_1024/Explorers%20shorts%20Sport%20Tech%20Cotton%20blend%20%28Small%29?unique=a6713d7",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/590/image_1024/Explorers%20shorts%20Sport%20Tech%20Cotton%20blend%20%28Small%29?unique=a6713d7", "/assets/drive/screenshot-2026-04-12-at-7-07-00-pm-png-1Eu-GO.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/explorers-shorts-sport-tech-cotton-blend-54",
    source: "demo",
  },
  {
    id: "dfi-006",
    slug: "hfd-cotton-short-sleeve-t-shirt",
    title: "HFD Cotton Short Sleeve T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    badge: "Best Seller",
    tags: ["hfd", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/374/image_1024/HFD%20Cotton%20Short%20Sleeve%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=8f94880",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/374/image_1024/HFD%20Cotton%20Short%20Sleeve%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=8f94880", "/assets/drive/img-5353-jpeg-1TeGQx.jpg"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-cotton-short-sleeve-t-shirt-39",
    source: "demo",
  },
  {
    id: "dfi-007",
    slug: "hfd-duty-50-50-short-sleeve-t-shirt",
    title: "HFD DUTY 50/50 Short Sleeve T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/294/image_1024/HFD%20DUTY%2050-50%20Short%20Sleeve%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=fc7ed0e",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/294/image_1024/HFD%20DUTY%2050-50%20Short%20Sleeve%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=fc7ed0e", "/assets/drive/screenshot-2026-04-12-at-7-06-43-pm-png-1IAHwT.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-5050-short-sleeve-t-shirt-42",
    source: "demo",
  },
  {
    id: "dfi-008",
    slug: "hfd-duty-carhart-1-4-zip-carhart-full-zip",
    title: "HFD DUTY Carhart 1/4 zip - Carhart full zip",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 12000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/479/image_1024/HFD%20DUTY%20Carhart%201-4%20zip%20-%20Carhart%20full%20zip%20%28Small%2C%20None%29?unique=24be6a9",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/479/image_1024/HFD%20DUTY%20Carhart%201-4%20zip%20-%20Carhart%20full%20zip%20%28Small%2C%20None%29?unique=24be6a9", "/assets/drive/screenshot-2026-04-21-at-2-00-20-pm-png-1aO_6I.png"],
    featured: true,
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-carhart-14-zip-carhart-full-zip-37",
    source: "demo",
  },
  {
    id: "dfi-009",
    slug: "hfd-duty-cotton-long-sleeve-athletic-fit-t-shirt",
    title: "HFD DUTY Cotton Long Sleeve Athletic Fit T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3400,
    tags: ["hfd", "duty", "shirt", "long-sleeve"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/254/image_1024/HFD%20DUTY%20Cotton%20Long%20Sleeve%20Athletic%20Fit%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=2642caa",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/254/image_1024/HFD%20DUTY%20Cotton%20Long%20Sleeve%20Athletic%20Fit%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=2642caa", "/assets/drive/img-8534-jpg-1cnRtK.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-cotton-long-sleeve-athletic-fit-t-shirt-40",
    source: "demo",
  },
  {
    id: "dfi-010",
    slug: "hfd-duty-cotton-long-sleeve-loose-fit-t-shirt",
    title: "HFD DUTY Cotton Long Sleeve Loose Fit T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3400,
    tags: ["hfd", "duty", "shirt", "long-sleeve"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/43/image_1024/HFD%20DUTY%20Cotton%20Long%20Sleeve%20Loose%20Fit%20T-Shirt?unique=492761b",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/43/image_1024/HFD%20DUTY%20Cotton%20Long%20Sleeve%20Loose%20Fit%20T-Shirt?unique=492761b", "/assets/drive/screenshot-2026-04-12-at-7-08-36-pm-png-1pAABY.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-cotton-long-sleeve-loose-fit-t-shirt-43",
    source: "demo",
  },
  {
    id: "dfi-011",
    slug: "hfd-duty-cotton-short-sport-tech",
    title: "HFD DUTY Cotton Short Sport Tech",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 2500,
    badge: "Best Seller",
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/718/image_1024/HFD%20DUTY%20Cotton%20Short%20Sport%20Tech%20%28Small%29?unique=303ebee",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/718/image_1024/HFD%20DUTY%20Cotton%20Short%20Sport%20Tech%20%28Small%29?unique=303ebee", "/assets/drive/screenshot-2026-04-19-at-8-07-11-pm-png-1szyyS.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-cotton-short-sport-tech-64",
    source: "demo",
  },
  {
    id: "dfi-012",
    slug: "hfd-duty-dfnd-t-shirt",
    title: "HFD DUTY DFND T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/44/image_1024/HFD%20DUTY%20DFND%20T-Shirt?unique=3dffec2",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/44/image_1024/HFD%20DUTY%20DFND%20T-Shirt?unique=3dffec2", "/assets/drive/s-logo-png-1iRV58.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-dfnd-t-shirt-44",
    source: "demo",
  },
  {
    id: "dfi-013",
    slug: "hfd-duty-dfnd-embroidered-hoodie",
    title: "HFD DUTY Dfnd embroidered Hoodie",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 12000,
    tags: ["hfd", "duty", "hoodie"],
    image: "https://www.defendfreedomindustries.com/web/image/product.template/36/image_1024/HFD%20DUTY%20Dfnd%20embroidered%20Hoodie?unique=f98d955",
    images: ["https://www.defendfreedomindustries.com/web/image/product.template/36/image_1024/HFD%20DUTY%20Dfnd%20embroidered%20Hoodie?unique=f98d955", "/assets/drive/img-4925-jpg-17ZbY2.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-dfnd-embroidered-hoodie-36",
    source: "demo",
  },
  {
    id: "dfi-014",
    slug: "hfd-duty-golden-nights",
    title: "HFD DUTY GOLDEN NIGHTS",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/678/image_1024/HFD%20DUTY%20GOLDEN%20NIGHTS%20%28Small%2C%20Firefighter%29?unique=9bae698",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/678/image_1024/HFD%20DUTY%20GOLDEN%20NIGHTS%20%28Small%2C%20Firefighter%29?unique=9bae698", "/assets/drive/img-4826-jpg-1RyfBW.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-golden-nights-63",
    source: "demo",
  },
  {
    id: "dfi-015",
    slug: "hfd-duty-los-angeles-apparel-t-shirt-50-50",
    title: "HFD DUTY Los Angeles Apparel T-Shirt 50/50",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/414/image_1024/HFD%20DUTY%20Los%20Angeles%20Apparel%20T-Shirt%2050-50%20%28Small%2C%20Firefighter%29?unique=f708742",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/414/image_1024/HFD%20DUTY%20Los%20Angeles%20Apparel%20T-Shirt%2050-50%20%28Small%2C%20Firefighter%29?unique=f708742", "/assets/drive/img-4919-jpg-1-IgNr.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-los-angeles-apparel-t-shirt-5050-41",
    source: "demo",
  },
  {
    id: "dfi-016",
    slug: "hfd-duty-new-era-long-sleeve",
    title: "HFD DUTY NEW ERA Long Sleeve",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3400,
    tags: ["hfd", "duty", "long-sleeve"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/638/image_1024/HFD%20DUTY%20NEW%20ERA%20Long%20Sleeve%20%28Small%2C%20Firefighter%29?unique=edff355",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/638/image_1024/HFD%20DUTY%20NEW%20ERA%20Long%20Sleeve%20%28Small%2C%20Firefighter%29?unique=edff355", "/assets/drive/screenshot-2026-04-12-at-7-06-43-pm-png-1D6Qfe.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-long-sleeve-61",
    source: "demo",
  },
  {
    id: "dfi-017",
    slug: "hfd-duty-new-era-short-sleeve",
    title: "HFD DUTY NEW ERA Short Sleeve",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/606/image_1024/HFD%20DUTY%20NEW%20ERA%20Short%20Sleeve%20%28Small%2C%20Firefighter%29?unique=86c2302",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/606/image_1024/HFD%20DUTY%20NEW%20ERA%20Short%20Sleeve%20%28Small%2C%20Firefighter%29?unique=86c2302", "/assets/drive/richardson-7-panel-laser-mesh-2-jpg-15Qy7A.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-short-sleeve-62",
    source: "demo",
  },
  {
    id: "dfi-018",
    slug: "hfd-duty-new-era-pull-over-embroidery",
    title: "HFD DUTY New Era Pull Over Embroidery",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 5200,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/334/image_1024/HFD%20DUTY%20New%20Era%20Pull%20Over%20Embroidery%20%28Small%2C%20Firefighter%29?unique=30a8f2d",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/334/image_1024/HFD%20DUTY%20New%20Era%20Pull%20Over%20Embroidery%20%28Small%2C%20Firefighter%29?unique=30a8f2d", "/assets/drive/ao-richardson-112-jpg-17uLi0.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-pull-over-embroidery-34",
    source: "demo",
  },
  {
    id: "dfi-019",
    slug: "hfd-duty-new-era-cotton-full-zip",
    title: "HFD DUTY New Era cotton full zip",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 5000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/134/image_1024/HFD%20DUTY%20New%20Era%20cotton%20full%20zip%20%28Small%2C%20Firefighter%29?unique=d03e4de",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/134/image_1024/HFD%20DUTY%20New%20Era%20cotton%20full%20zip%20%28Small%2C%20Firefighter%29?unique=d03e4de", "/assets/drive/richardson-on-feild-laser-mesh-jpg-1cupLN.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-cotton-full-zip-35",
    source: "demo",
  },
  {
    id: "dfi-020",
    slug: "hfd-duty-new-era-pull-over-hoodie",
    title: "HFD DUTY New Era pull over hoodie",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 5000,
    tags: ["hfd", "duty", "hoodie"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/484/image_1024/HFD%20DUTY%20New%20Era%20pull%20over%20hoodie%20%28Small%2C%20Firefighter%29?unique=8f4416b",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/484/image_1024/HFD%20DUTY%20New%20Era%20pull%20over%20hoodie%20%28Small%2C%20Firefighter%29?unique=8f4416b", "/assets/drive/richardson-7-panel-laser-mesh-1-1mMayd.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-pull-over-hoodie-33",
    source: "demo",
  },
  {
    id: "dfi-021",
    slug: "hfd-duty-new-era-9seventy-perforated-snapback-cap",
    title: "HFD DUTY New Era\u00ae 9SEVENTY\u00ae Perforated Snapback Cap",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "patriot-essentials",
    priceCents: 3500,
    badge: "New",
    tags: ["hfd", "duty", "cap"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/597/image_1024/HFD%20DUTY%20New%20Era%C2%AE%209SEVENTY%C2%AE%20Perforated%20Snapback%20Cap?unique=4390ca4",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/597/image_1024/HFD%20DUTY%20New%20Era%C2%AE%209SEVENTY%C2%AE%20Perforated%20Snapback%20Cap?unique=4390ca4", "/assets/drive/richardson-7-panel-trucker-mesh-2-13VF_I.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-new-era-9seventy-perforated-snapback-cap-59",
    source: "demo",
  },
  {
    id: "dfi-022",
    slug: "hfd-duty-richardson-112-classic",
    title: "HFD DUTY Richardson 112 / classic",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/130/image_1024/HFD%20DUTY%20Richardson%20112%20-%20classic%20%28Medium%29?unique=71c1a08",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/130/image_1024/HFD%20DUTY%20Richardson%20112%20-%20classic%20%28Medium%29?unique=71c1a08", "/assets/drive/richardson-7-panel-trucker-mesh-1-1yiQo4.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-richardson-112-classic-28",
    source: "demo",
  },
  {
    id: "dfi-023",
    slug: "hfd-duty-richardson-7-panel-flat-bill",
    title: "HFD DUTY Richardson 7 Panel Flat Bill",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/30/image_1024/HFD%20DUTY%20Richardson%207%20Panel%20Flat%20Bill?unique=718b547",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/30/image_1024/HFD%20DUTY%20Richardson%207%20Panel%20Flat%20Bill?unique=718b547", "/assets/drive/vivone-foam-trucker-hat-2-1hgkxM.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-richardson-7-panel-flat-bill-30",
    source: "demo",
  },
  {
    id: "dfi-024",
    slug: "hfd-duty-richardson-on-field-hat-melon-type",
    title: "HFD DUTY Richardson On Field Hat / Melon type",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "patriot-essentials",
    priceCents: 3200,
    tags: ["hfd", "duty", "hat"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/128/image_1024/HFD%20DUTY%20Richardson%20On%20Field%20Hat%20-%20Melon%20type%20%28Medium%29?unique=31359dc",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/128/image_1024/HFD%20DUTY%20Richardson%20On%20Field%20Hat%20-%20Melon%20type%20%28Medium%29?unique=31359dc", "/assets/drive/vivone-foam-trucker-hat-1-1H86tE.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-richardson-on-field-hat-melon-type-29",
    source: "demo",
  },
  {
    id: "dfi-025",
    slug: "hfd-duty-royal-apparel-t-shirt",
    title: "HFD DUTY Royal Apparel T-Shirt",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3000,
    tags: ["hfd", "duty", "shirt"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/214/image_1024/HFD%20DUTY%20Royal%20Apparel%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=80ea1a7",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/214/image_1024/HFD%20DUTY%20Royal%20Apparel%20T-Shirt%20%28Small%2C%20Firefighter%29?unique=80ea1a7", "/assets/drive/richardson-112-1hi01c.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-royal-apparel-t-shirt-38",
    source: "demo",
  },
  {
    id: "dfi-026",
    slug: "hfd-duty-sport-tek-sport-wick-stretch-jogger",
    title: "HFD DUTY Sport-Tek\u00ae Sport-Wick\u00ae Stretch Jogger",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 3500,
    tags: ["hfd", "duty", "jogger"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/598/image_1024/HFD%20DUTY%20Sport-Tek%C2%AE%20Sport-Wick%C2%AE%20Stretch%20Jogger?unique=a4d7602",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/598/image_1024/HFD%20DUTY%20Sport-Tek%C2%AE%20Sport-Wick%C2%AE%20Stretch%20Jogger?unique=a4d7602", "/assets/drive/compare-17aN2Y.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-sport-tek-sport-wick-stretch-jogger-60",
    source: "demo",
  },
  {
    id: "dfi-027",
    slug: "hfd-duty-synthetic-7-inch-shorts-sport-tech",
    title: "HFD DUTY Synthetic 7 inch Shorts sport tech",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "hfd-duty",
    priceCents: 2500,
    tags: ["hfd", "duty", "shorts"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/45/image_1024/HFD%20DUTY%20Synthetic%207%20inch%20Shorts%20sport%20tech?unique=6ca5f5b",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/45/image_1024/HFD%20DUTY%20Synthetic%207%20inch%20Shorts%20sport%20tech?unique=6ca5f5b", "/assets/drive/img-6937-heic-13Mxtb.jpg"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-synthetic-7-inch-shorts-sport-tech-45",
    source: "demo",
  },
  {
    id: "dfi-028",
    slug: "hfd-duty-vivone-special-foam-trucker-hat",
    title: "HFD DUTY Vivone special / Foam Trucker Hat",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "patriot-essentials",
    priceCents: 2600,
    tags: ["hfd", "duty", "hat"],
    image: "https://www.defendfreedomindustries.com/web/image/product.template/31/image_1024/HFD%20DUTY%20Vivone%20special%20-%20Foam%20Trucker%20Hat?unique=36f3c29",
    images: ["https://www.defendfreedomindustries.com/web/image/product.template/31/image_1024/HFD%20DUTY%20Vivone%20special%20-%20Foam%20Trucker%20Hat?unique=36f3c29", "/assets/drive/998413f0-7aa6-4026-8d95-da614621f484-png-1wpbYa.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-vivone-special-foam-trucker-hat-31",
    source: "demo",
  },
  {
    id: "dfi-029",
    slug: "hfd-duty-bomber-jacket",
    title: "HFD Duty Bomber Jacket",
    description: "Premium first-responder apparel built for performance, comfort, and pride.",
    currency: "USD",
    category: "off-duty-fire",
    priceCents: 8500,
    badge: "New",
    tags: ["hfd", "duty"],
    image: "https://www.defendfreedomindustries.com/web/image/product.product/88/image_1024/HFD%20Duty%20Bomber%20Jacket%20%28Small%2C%20Firefighter%29?unique=343cc34",
    images: ["https://www.defendfreedomindustries.com/web/image/product.product/88/image_1024/HFD%20Duty%20Bomber%20Jacket%20%28Small%2C%20Firefighter%29?unique=343cc34", "/assets/drive/ed846aac-ef75-4841-9b61-f16fa9876f19-png-1jBXR0.png"],
    inStock: true,
    sourceUrl: "https://www.defendfreedomindustries.com/shop/hfd-duty-bomber-jacket-26",
    source: "demo",
  },
];